// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Teaism",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "Teaism",
            targets: ["AppModule"],
            bundleIdentifier: "com.infinity.Teaism",
            teamIdentifier: "SY69L98Q38",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.green),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("Resources/home.mov"),
                .process("Resources/enter.mov"),
                .process("Resources/home.wav"),
                .process("Resources/session.mp3"),
                .process("Resources/voice.mp3"),
            ]
        )
    ],
    swiftLanguageVersions: [.v5]
)
